fitnotes/urls.py
from django.conf.urls import *
from django.contrib import admin

from fitnotes.views import home,Fitlogs_View,fitforum,Register_User
from fitnotes.fitlogs.views import FitLog_Handler, Process_data

from django.contrib.auth.views import login, logout



admin.autodiscover()

urlpatterns = patterns('',

	(r'^admin/', include(admin.site.urls)),
	(r'^$',home),
	(r'^fitlogs/$',Fitlogs_View),
	(r'^fitlogs/logit$',FitLog_Handler),
	(r'^fitlogs/progress$',Process_data),
	
	(r'^fitforums/$',fitforum),
	
	
	(r'^login/$',  login, {'extra_context': {'next': '/'}}),
	(r'^logout/$', logout,{'next_page': '/'}),
	
	(r'^signup/$', Register_User),
	
)
              

fitnotes/fitforums/models.py
from django.db import models

# Create your models here.

class Comment(models.Model):
    comment = models.TextField()
    by = models.CharField()
    
class Disscussion(models.Model):
    comments = models.m

fitnotes/fitlogs/models.py
from django.db import models
from django.contrib.auth.models import User
 
   
# Create your models here.
class Exercise(models.Model):
    workout=models.CharField(max_length=80)
    duration=models.CharField(max_length=20)
    reps=models.CharField(max_length=20)
    resistance=models.CharField(max_length=40)
    created_by = models.CharField(max_length=60)
    def __unicode__(self):
        return self.workout

class FitLog(models.Model):
    Created_by = models.CharField(max_length=60)
    log_Date=models.DateField()
    type = models.CharField(max_length = 30,)
    workouts = models.ManyToManyField(Exercise,blank = True)
    weight = models.CharField(max_length=60,)
    def __unicode__(self):
		return u'%s' % self.log_Date
        
    class Meta:
		ordering =['-log_Date']

class UserProfile(models.Model):
	user = models.OneToOneField(User)
	journalEntries = models.ManyToManyField(FitLog, blank = True)

    
    
	

fitnotes/forms.py
from django.contrib.auth.models import User
from django import forms
from fitnotes.fitlogs.models import FitLog,Exercise,UserProfile
from django.utils.translation import ugettext_lazy as _
from django.forms import ModelForm

from django.contrib.admin.widgets import AdminDateWidget

class RegistrationForm(forms.Form):

    username = forms.RegexField(regex=r'^[a-zA-Z0-9_-]{3,10}$', max_length=10,)
    email = forms.EmailField(label=_("E-mail"))
    password1 = forms.CharField(widget=forms.PasswordInput(render_value=False),)
    password2 = forms.CharField(widget=forms.PasswordInput(render_value=False),)
    
    def clean_username(self):
        existing_user = User.objects.filter(username__iexact=self.cleaned_data['username'])
        if existing_user.exists():
            raise forms.ValidationError(_("A user with that username already exists."))
        else:
            return self.cleaned_data['username']
        
    def clean(self):
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_("The two password fields didn't match."))
            
            elif len(self.cleaned_data['password1']) < 5:
                raise forms.ValidationError(_("Password must be 6 or more characters."))
                
        return self.cleaned_data
    
class ExerciseForm(ModelForm):
    class Meta:
        model = Exercise
        exclude=('created_by',)
        widgets = {
            'workout': forms.TextInput(attrs={ 'data-provide': 'typeahead','data-items':"5",
                                              'data-source':'["Pull Ups","Chin Ups", "Barbell Bench Press", "Barbell Incline Bench Press","Incline Dumbbell Flyes","Dumbbell Bench Press","Dumbbell Incline Press","Triceps Pressdown","Lying Triceps Extension","Cable Overhead Triceps Extension","Standing Calf Raises","Seated Calf Raises","Squats","One-arm Dumbbell Row","Wide-Grip Pulldown","Standing Pulldown","Straight-Arm Pulldown","Run","Boxing","Hiking","Swimming","Barbell Curl","Dumbbell Curl","Incline Dumbbell Curl","One-Arm High Cable Curl","Crunches","Sit-Ups","Oblique Crunches","Dumbbell Shoulder Press","Side Lateral Raise","One-Arm Front Cable Raises","High Cable Rear Delt Flyes","Dumbbell Shrug","Leg Press","Leg Press One-Leg","Deadlift","Leg Extensions","Romanian Deadlift","Lying Leg Curl","Weighted Bent-Knee Hip Raise","Cable Crunch","Standing Cable Wood Chopper"]' }),
        }
       
class FitlogForm(ModelForm):
  
    class Meta:
        model= FitLog
        exclude=('Created_by','workouts')


    
            

fitnotes/fitforums/views.py
# Create your views here.

fitnotes/fitlogs/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.forms.formsets import formset_factory

from fitnotes.forms import ExerciseForm,FitlogForm
from fitnotes.fitlogs.models import FitLog,Exercise
from django.contrib.auth.decorators import login_required



def Process_data(request):
    data = FitLog.objects.filter(Created_by=request.user,log_Date__range=["2012-08-01", "2013-02-28"])
    total = num = 0
    datelist = []
    for d in data:
        datelist.append(d.log_Date)
        total +=  int(d.weight)
        num += 1
    aver = total / num
    
    return render_to_response('fitlogs/progress.html',
                              {'user':True, 'username':request.user,'aver':aver,'dates':datelist})
    



@login_required(login_url='/login/')
def FitLog_Handler(request):    
    exFormSet = formset_factory(ExerciseForm,extra=1)
    
    if request.method =='POST':
        fitform = FitlogForm(request.POST)    
        formset = exFormSet(request.POST)
        
        if 'del_workout' in request.POST:
            formset,fitform = formset_handler(request,exFormSet,-1)
        
        elif 'add_workout' in request.POST:
            formset,fitform = formset_handler(request,exFormSet,1)
        
        elif 'submit' in request.POST:                        
            if fitform.is_valid() and formset.is_valid():
                submit_form(request,fitform,formset)
                return HttpResponseRedirect("/fitlogs/")
    else:
        fitform = FitlogForm()
        formset = exFormSet()
        
    return render_to_response('fitlogs/logform.html',
                            {'user':True,'username':request.user,'form':fitform,'formset':formset},
                            context_instance=RequestContext(request))

def submit_form(request,fitform,formset):
    log = fitform.save(commit=False)
    log.Created_by = request.user
    log.save()
    for values in formset.cleaned_data:
        exer = Exercise(workout=values['workout'],reps = values['reps'], 
                     duration = values['duration'], resistance=values['resistance'], created_by = request.user)
        exer.save()
        log.workouts.add(exer)
    
def formset_handler(request, exFormSet,num):
    cp = request.POST.copy()
    cp['form-TOTAL_FORMS'] = int(cp['form-TOTAL_FORMS']) + num
    formset = exFormSet(cp,prefix='form')
    fitform = FitlogForm(cp) 
    return formset,fitform

fitnotes/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib import auth
from django.http import HttpResponseRedirect

from fitnotes.fitlogs.models import UserProfile,FitLog
from fitnotes.forms import RegistrationForm
from django.contrib.auth.models import User


def home(request):
	if request.user.is_authenticated():
		return render_to_response('home.html',
								{'user':True,'username': request.user})
	else:
	   return render_to_response('home.html')

def Fitlogs_View(request):	
	if request.user.is_authenticated():
		userlogs = FitLog.objects.filter(Created_by=request.user)
		return render_to_response('fitlogs/userlogs.html',
								{'user':True,'username':request.user,'logs':userlogs})
	else:
		return render_to_response('fitlogs/userlogs.html',)
	
	
def fitforum(request):
	if request.user.is_authenticated():
		return render_to_response('fitforums.html',
								{'user':True,'username':request.user})
	else:
	   return render_to_response('fitforums.html')

def Register_User(request):
	if request.method =='POST':
		form= RegistrationForm(request.POST)
					
		if form.is_valid():
			cd= form.cleaned_data
			newuser= User.objects.create_user(cd['username'].lower(), cd['email'], cd['password1'])
																																																														 
			new_profile = UserProfile(user=newuser,)
			new_profile.save()
		
			user = auth.authenticate(username=cd['username'].lower(), password=cd['password1'])
			if user is not None and user.is_active:
				auth.login(request, user)
				return HttpResponseRedirect("/")
	else:
		
		form = RegistrationForm()
		
	return render_to_response('registration/signup.html',
							{'form': form},
							context_instance=RequestContext(request))
	

fitnotes/templates/base.html
<!DOCTYPE html>
	<html>
    <head><script type='text/javascript'>window.mod_pagespeed_start = Number(new Date());</script>
        <title>FitNotes</title>
                
        
       <link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,700"rel=stylesheet type='text/css'>

                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                        <link href="/static/bootstrap-responsive.css" rel="stylesheet">
                      
                       
                   
                    <link href="/static/bootstrap.css" rel="stylesheet" type="text/css">
             
           
                <link rel="shortcut icon" href="/static/cool.ico"/>
            
        </head>
        <body>

                
            {% block content %}

            {% endblock %}
                
         <script src="/static/jquery.js"></script>
		<script src="/static/bootstrap.js"></script>
		<script>$(".collapse").collapse();</script>
		<script>$('.typeahead').typeahead();</script>
            </body>
</html>

fitnotes/templates/fitforums.html
{% extends "base.html" %}

{% block content %}
<nav>
				<div class="navbar navbar-fixed-top navbar-inverse">
				      <div class="navbar-inner">
				        <div class="container">
				        	
				          <a class="brand" href="/">FitNotes</a>
				          			
									<div class="nav pull-right">
							           <div class="btn-group">
							           	
									  <button class="btn btn btn-inverse">{% if user %}{{username}}{% else %}<a href="/login">Login</a>{% endif %}</button>
									  <button class="btn btn-inverse dropdown-toggle" data-toggle="dropdown">
									    <span class="caret"></span>
									  </button>
										<ul class="dropdown-menu"> {% if user %}
							            	    	
								      <li><a href="/profile">Profile</a></li>
								      <li class="divider"></li>
								          <li><a href="/logout">Logout</a></li>
								    {% else %}
								    
							              <li><a href="/login">Login</a></li>
							              <li class="divider"></li>
							              <li><a href="/signup">Signup</a></li>
							              
							             {% endif %}
							            </ul>
											</div>
							          </div>
				          <div class="nav-collapse collapse">
				            <ul class="nav">
				            	
				            	<li class="divider-vertical"></li>
				              <li >
				                <a href="/">Home</a>
				              </li>
				              <li >
				                <a href="/fitlogs">FitLogs</a>
				              </li>
				              <li class="active">
				                <a href="/fitforums">FitForums</a>
				              </li>
				            				              
								</ul>
				            
				          </div>
				        </div>
				      </div>
				    </div>
				</nav>
				<br /><br /><br />
				
				<div class="container">
				<div class="alert alert-info">
					
						  
						  <h3 class="alert-heading">Coming Soon!!</h3>
						  A forum where you can discuss workout plans, diets, or meal recipes with other users. 
						  
						</div>
				</div>

				
{% endblock %}

fitnotes/templates/fitlogs.html
{% extends "base.html" %}

{% block content %}

			<nav>
				<div class="navbar navbar-fixed-top navbar-inverse">
				      <div class="navbar-inner">
				        <div class="container">
				        	
				          <a class="brand" href="/">FitNotes</a>
				          
									<div class="nav pull-right">
							           <div class="btn-group">
							           	
									  <button class="btn btn btn-inverse">{% if user %}{{username}}
									  							{% else %}<a href="/login">Login</a>{% endif %}</button>
									  <button class="btn btn-inverse dropdown-toggle" data-toggle="dropdown">
									    <span class="caret"></span>
									  </button>
										<ul class="dropdown-menu"> {% if user %}
							            	    	
								      <li><a href="/profile">Profile</a></li>
								      <li class="divider"></li>
								          <li><a href="/logout">Logout</a></li>
								    {% else %}
								    
							              <li><a href="/login">Login</a></li>
							              <li class="divider"></li>
							              <li><a href="/signup">Signup</a></li>
							              
							             {% endif %}
							            </ul>
											</div>
							          </div>
							          
				          <div class="nav-collapse collapse">
				            <ul class="nav">
				            	
				            	<li class="divider-vertical"></li>
				              <li >
				                <a href="/">Home</a>
				              </li>
				              <li class="active">
				                <a href="/fitlogs">FitLogs</a>
				              </li>
				              <li >
				                <a href="/fitforums">FitForums</a>
				              </li>
				            				              
								</ul>
				            
				          </div>
				        </div>
				      </div>
				    </div>
				</nav>
				<br /><br /><br />
				
				
<div class="container">
	<div class="row-fluid">
					
						

						 
					
			
						{% block view %}

           				 {% endblock %}
                
																	      <!--Body content-->
			
	</div>
</div>
											
{% endblock %}

fitnotes/templates/fitlogs/logform.html
{% extends "fitlogs.html" %}



{% block view %}							
									<ul  class="nav nav-tabs">
									          <li ><a href="/fitlogs/" >Journal</a></li>
									          <li class="active"><a href="/fitlogs/logit"> Logit</a></li>
									          <li><a href="/fitlogs/progress"> Progress</a></li>
									        
									    </ul>
								
								
								<form class="form-horizontal" action="" method="post">
									  	{% csrf_token %} 
								            <fieldset>
									
									{{ formset.management_form }}
									<div class="well">
								        <div class="control-group">
								            <label class="control-label" for="id_log_Date">Date</label>
								            <div class="controls">
								             
								              {{form.log_Date}}
								              
								              	    {% for error in form.log_Date.errors %}
														        <span class="label label-important">{{ error|escape }}</span>
														    {% endfor %}
								              <p class="help-block">Enter date of your workout. <br>
								              	Preferred format: YYYY-MM-DD | 2012-08-18</p>
								            </div>
								          </div>
								          
								          <div class="control-group">
								            <label class="control-label" for="id_type">Type of Day</label>
								            <div class="controls">
								       
								              {{form.type}}
								              	    {% for error in form.type.errors %}
														        <span class="label label-important">{{ error|escape }}</span>
														    {% endfor %}
								              <p class="help-block">Chest Day? Leg Day? Cardio Day?</p>
								            </div>
								          </div>
										
										<div class="control-group">
								            <label class="control-label" for="id_weight">Today's Weight</label>
								            <div class="controls">
								            
								             {{form.weight}}
								              	    {% for error in form.weight.errors %}
														        <span class="label label-important">{{ error|escape }}</span>
														    {% endfor %}
								              <p class="help-block">Enter your current weight.</p>
								            </div>
								          </div>
								       </div>					          
								          {% for form in formset %}
								          
								          
								          	
													 <div class="control-group well">
								       	
												 <label class="control-label" for="id_workout">Workout: </label>
												 <input class="btn btn-primary btn-small pull-right" title='Del' type='submit' name='del_workout' value='Delete' />
										            <div class="controls">
										            
										             {{form.workout}}
										             	{% for error in form.workout.errors %}
														        <span class="label label-important">{{ error|escape }}</span>
														    {% endfor %}
										              <p class="help-block">If your specific workout is not found, enter as you desire.</p>
										             <br/>
										          
										            </div>
										            
										            <label class="control-label" for="id_duration">Duration: </label>
										            <div class="controls">
										            
										             {{form.duration}}
								              	    {% for error in form.duration.errors %}
														        <span class="label label-important">{{ error|escape }}</span>
														    {% endfor %}										             
										            </div>
										            
										          <label class="control-label" for="id_reps">Reps: </label>
										            <div class="controls">
										             
										              {{form.reps}}
								              	    {% for error in form.reps.errors %}
														        <span class="label label-important">{{ error|escape }}</span>
														    {% endfor %}			
										            </div>
										            
										           <label class="control-label" for="id_resistance">Resistance: </label>
										            <div class="controls">
										        
										             {{form.resistance}}
								              	    {% for error in form.resistance.errors %}
														        <span class="label label-important">{{ error|escape }}</span>
														    {% endfor %}										             
										            </div>
										           
								       
								        
								        </div>
								       {% endfor %}
								       								          														
								</fieldset>
								    
								  
								  <div class="modal-footer">
								  	<input class="btn btn-primary pull-left" title='Add' type='submit' name='add_workout' value='Add' />
								    <input class="btn btn-primary" type="submit" name='submit' value="Submit">
								  </div>
								  </form>	
														
{% endblock %}	

fitnotes/templates/fitlogs/logform_test.html
{% extends "fitlogs.html" %}

{% block view %}							

									<ul  class="nav nav-tabs">
									          <li ><a href="/fitlogs/" >{{username}}</a></li>
									          <li class="active"><a href="/fitlogs/logit"> Logit</a></li>
									          <li><a href="#"> Progress</a></li>
									        
									    </ul>
								
								
								<form class="form-horizontal" action="" method="post">
									  	{% csrf_token %} 
								            <fieldset>
									
									{{ formset.management_form }}
									
								        <div class="control-group">
								            <label class="control-label" for="id_log_Date">Date</label>
								            <div class="controls">
								             
								              {{form.log_Date}}
								              
								              	    {% for error in form.log_Date.errors %}
														        <span class="label label-important">{{ error|escape }}</span>
														    {% endfor %}
								              <p class="help-block">Enter date of your workout.</p>
								            </div>
								          </div>
								          
								          <div class="control-group">
								            <label class="control-label" for="id_type">Type of Day</label>
								            <div class="controls">
								       
								              {{form.type}}
								              	    {% for error in form.type.errors %}
														        <span class="label label-important">{{ error|escape }}</span>
														    {% endfor %}
								              <p class="help-block">Chest Day? Leg Day? Cardio Day?</p>
								            </div>
								          </div>
										
										<div class="control-group">
								            <label class="control-label" for="id_weight">Today's Weight</label>
								            <div class="controls">
								            
								             {{form.weight}}
								              	    {% for error in form.weight.errors %}
														        <span class="label label-important">{{ error|escape }}</span>
														    {% endfor %}
								              <p class="help-block">Enter your current weight.</p>
								            </div>
								          </div>
								          								          
								          {% for form in formset %}
								          {{form.errors}}
								          
								          	
 												 <div class="span12">
                                                      <table class="table table-striped table-hover table-bordered table-condensed">
                                                                                <thead>
                                                                                    
                                                                              
                                                                                
                                                                                  <tr>
                                                                                   
                                                                                    <th>Workout</th>
                                                                                    <th>Duration</th>
                                                                                    <th>Reps</th>
                                                                                    <th>Resistance</th>
                                                                                    
                                                                                  </tr>
                                                                                </thead>
                                                                                
                                                                                <tbody>
                                                                                
                                                                                  <tr>
                                                                                  
                                                                                   
                                                                                    <td>{{form.workout}}</td>
                                                                                    <td>{{form.duration}}</td>
                                                                                    <td> {{form.reps}}</td>
                                                                                    <td>  {{form.resistance}}</td>
                                                                                    
                                                                                   
                                                                                  </tr>
                                                                                
                                                                                </tbody>
                                                                              </table>
                                                                              </div>

								       
								        <input class="btn btn-primary" title='Del' type='submit' name='del_workout' value='Delete' />
								        
								       {% endfor %}
								       								          														
								</fieldset>
								    
								  
								  <div class="modal-footer">
								  	<input class="btn btn-primary" title='Add' type='submit' name='add_workout' value='Add' />
								    <input class="btn btn-primary" type="submit" name='submit' value="Submit">
								  </div>
								  </form>	
{% endblock %}	

fitnotes/templates/fitlogs/progress.html
{% extends 'fitlogs.html'%}

{% block view %}
									<ul  class="nav nav-tabs">
									          <li ><a href="/fitlogs/" >Journal</a></li>
									          <li ><a href="/fitlogs/logit"> Logit</a></li>
									          <li class="active"><a href="/fitlogs/progress"> Progress</a></li>
									        
									    </ul>




average for month: {{ aver }}
{% for month in dates %}
	{{month}}

{%endfor%}






{% endblock %}

fitnotes/templates/fitlogs/userlogs.html
{% extends "fitlogs.html" %}

{% block view %}


								        <ul  class="nav nav-tabs">
									          <li class="active"><a href="/fitlogs/" >Journal</a></li>
									          <li><a href="/fitlogs/logit"> Logit</a></li>
									          <li><a href="/fitlogs/progress"> Progress</a></li>
									        
									    </ul>
								<div class="accordion" id="accordion2">
											{% if logs %}						
												{% for log in logs.all %}
												
													 	
										            <div class="accordion-group">
										              <div class="accordion-heading">
										                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#{{ forloop.counter }}" >
										                  Date: {{log.log_Date}}
										                </a>
										              </div>
										              <div id="{{ forloop.counter }}" class="accordion-body collapse in">
										                <div class="accordion-inner">
																		<div class="span12">
																		      <table class="table table-hover table-striped table-bordered table-condensed">
																		        <thead>
																		        	
																		          <tr>
																		            <th colspan="2">Type of Workout: {{log.type}}</th>
																		            <th>Current Weight: {{log.weight}} </th>
																		          </tr>
																		          <tr>
																		           
																		            <th>Workout</th>
																		            <th>Duration</th>
																		            <th>Reps</th>
																		            <th>Resistance</th>
																		            
																		          </tr>
																		        </thead>
																		        
																		        <tbody>
																		        	{% for workout in log.workouts.all %}
																		          <tr>
																		          
																		           
																		            <td>{{workout.workout}}</td>
																		            <td>{{workout.duration}}</td>
																		            <td>{{workout.reps}}</td>
																		            <td> {{workout.resistance}}</td>
																		            
																		           
																		          </tr>
																		          {% endfor %}
																		        </tbody>
																		      </table>
																		    </div>
																		    
										                </div>
										              </div>
										            </div>
										           					
										         
														{% endfor %}
														
																		{% else %}
																<p>No logs found</p>
																{% endif %}
										</div>			
										
{% endblock %}	

fitnotes/templates/home.html
{% extends "base.html" %}

{% block content %}
<nav>
				<div class="navbar navbar-fixed-top navbar-inverse">
				      <div class="navbar-inner">
				        <div class="container">
				        	
				          <a class="brand" href="/">FitNotes</a>
				          
									<div class="nav pull-right">
							           <div class="btn-group">
							           	
									  <button class="btn btn btn-inverse">{% if user %}{{username}}{% else %}<a href="/login">Login</a>{% endif %}</button>
									  <button class="btn btn-inverse dropdown-toggle" data-toggle="dropdown">
									    <span class="caret"></span>
									  </button>
										<ul class="dropdown-menu"> {% if user %}
							            	    	
								      <li><a href="/profile">Profile</a></li>
								      <li class="divider"></li>
								          <li><a href="/logout">Logout</a></li>
								    {% else %}
								    
							              <li><a href="/login">Login</a></li>
							              <li class="divider"></li>
							              <li><a href="/signup">Signup</a></li>
							              
							             {% endif %}
							            </ul>
											</div>
							          </div>
							          
				          <div class="nav-collapse collapse">
				            <ul class="nav">
				            	
				            	<li class="divider-vertical"></li>
				              <li class="active">
				                <a href="/">Home</a>
				              </li>
				              <li >
				                <a href="/fitlogs">FitLogs</a>
				              </li>
				              <li >
				                <a href="/fitforums">FitForums</a>
				              </li>
				            				              
								</ul>
				            
				          </div>
				        </div>
				      </div>
				    </div>
				</nav>
				<br /><br /><br />
				
				
				
				
				
				<div class="container">
					
						{% block user_handler %}

           				 {% endblock %}
				<div class="alert alert-info">
					<h3 class="alert-heading">Welcome to FitNotes</h3>
									 <br />
						FitNotes is a simple fitness jounal. Log your workouts and keep track of your progress. You will also be able to interact with other members of FitNotes! Talk about the latest workout plans or share diets. 
						
						The site is in the early stages of development. Expect heavy redesign work.  
									  
						</div>
						
 
						</div>
				
{% endblock %}